import { MainLayout } from '@components/main-layout'
import { PraisesList } from '@components/praises'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Praise Yourself',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <MainLayout className="pt-10">
      <div className="space-y-2">
        <h1 className="text-4xl font-bold">
          Welcome to <span className="text-primary">Praise Yourself</span>
        </h1>
        <p className="text-base">
          Do you ever feel like you need a little pick-me-up? We got you! <br />
          Here you can find a list of praises to help you feel better about yourself.
        </p>
      </div>

      <PraisesList className="mt-10" />
    </MainLayout>
  )
}
