import type { Metadata } from 'next'
import Image from 'next/image'

export const metadata: Metadata = {
  title: 'Praise Yourself',
  description: 'Generated by create next app',
}

export default function Home() {
  return <main className="container">Hello</main>
}
