import { MainLayout } from '@components/main-layout'
import { PraisesList } from '@components/praises'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Praise Yourself',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <MainLayout className="py-10">
      <div className="space-y-2">
        <h1 className="text-4xl font-bold">
          Welcome to <span className="text-primary">Praise Yourself</span>
        </h1>
        <p className="text-base">Here you can buy prises for yourself</p>
      </div>

      <PraisesList className="mt-10" />
    </MainLayout>
  )
}
